COMPARING PERFORMANCE OF MLP CLASSIFIER AND LOGISTIC REGRESSION CLASSIFIER ON MNIST DATASET

In [56]:
from sklearn.neural_network import MLPClassifier
import numpy as np

In [57]:
x = np.array([[0,0], [1,0], [0,1], [1,1], [1,1], [1,0], [0,0],[0,1]])

In [58]:
y = np.array([0,1,1,0,0,1,0,1])

In [63]:
mlp = MLPClassifier(activation='relu', hidden_layer_sizes=(10))
mlp.fit(x, y)

/Users/prachigarg/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [64]:
z = np.array([[1,0],[0,1],[0,0], [1,1]])
y_test = np.array([1, 1, 0, 0])
mlp.predict(z)

array([1, 1, 0, 0])

In [65]:
mlp.get_params()

{'activation': 'relu',
 'alpha': 0.0001,
 'batch_size': 'auto',
 'beta_1': 0.9,
 'beta_2': 0.999,
 'early_stopping': False,
 'epsilon': 1e-08,
 'hidden_layer_sizes': 10,
 'learning_rate': 'constant',
 'learning_rate_init': 0.001,
 'max_iter': 200,
 'momentum': 0.9,
 'nesterovs_momentum': True,
 'power_t': 0.5,
 'random_state': None,
 'shuffle': True,
 'solver': 'adam',
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': False,
 'warm_start': False}

In [66]:
mlp.score(z, y_test)

1.0

In [67]:
from sklearn import datasets

In [68]:
mnist = datasets.load_digits()

In [69]:
mnist.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(mnist.data, mnist.target, test_size=0.3)

In [100]:
mlp2 = MLPClassifier(activation='relu', hidden_layer_sizes = (110))
mlp.fit(X_train, Y_train)

/Users/prachigarg/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=10, learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [101]:
#mlp.predict(X_test)

In [102]:
#print(Y_test)
mlp.score(X_test, Y_test)

0.9351851851851852

In [103]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [104]:
logistic.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [105]:
logistic.predict(X_test)

array([1, 8, 0, 9, 2, 0, 1, 1, 1, 9, 4, 4, 2, 3, 2, 1, 4, 9, 1, 4, 3, 8,
       5, 3, 2, 4, 0, 6, 3, 0, 0, 3, 7, 2, 2, 5, 3, 1, 1, 6, 3, 7, 7, 9,
       8, 8, 9, 0, 6, 4, 2, 8, 6, 0, 5, 3, 7, 2, 8, 1, 3, 4, 0, 8, 4, 0,
       5, 2, 0, 4, 8, 2, 0, 8, 2, 0, 3, 7, 3, 4, 3, 0, 8, 9, 1, 8, 1, 1,
       6, 6, 9, 6, 0, 0, 7, 2, 4, 0, 3, 3, 3, 3, 2, 8, 8, 0, 1, 9, 5, 5,
       8, 1, 2, 0, 4, 7, 1, 9, 4, 3, 1, 3, 1, 7, 1, 6, 9, 0, 0, 9, 4, 5,
       1, 9, 2, 7, 1, 7, 1, 9, 4, 4, 6, 5, 7, 1, 1, 6, 6, 6, 5, 4, 0, 6,
       2, 3, 2, 0, 7, 3, 3, 2, 3, 5, 9, 1, 5, 4, 9, 8, 3, 1, 2, 1, 0, 4,
       4, 2, 4, 9, 8, 3, 2, 3, 2, 2, 7, 5, 7, 9, 8, 0, 2, 2, 2, 7, 9, 6,
       8, 1, 9, 2, 9, 8, 8, 6, 5, 6, 4, 4, 0, 6, 1, 8, 7, 2, 9, 6, 6, 6,
       2, 2, 2, 0, 3, 8, 8, 8, 1, 2, 9, 6, 4, 7, 2, 8, 6, 8, 2, 7, 2, 8,
       6, 7, 4, 4, 2, 9, 9, 7, 4, 9, 0, 6, 5, 5, 0, 3, 7, 3, 8, 1, 3, 8,
       0, 1, 6, 8, 1, 9, 6, 1, 2, 9, 7, 6, 2, 8, 5, 8, 2, 9, 7, 1, 5, 8,
       1, 2, 6, 2, 2, 3, 6, 0, 1, 2, 9, 3, 8, 1, 5,

In [106]:
logistic.score(X_test, Y_test)

0.9666666666666667

In [108]:
#LOGISTIC REGRESSION PERFORMS BETTER 